version: "3.8"

services:
  mongo:
    image: mongo

  express:
    image: node:current-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    depends_on:
      - mongo
    command: sh -c "npm install && npm start" 

  vue:
    image: node:current-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
    depends_on:
      - express
    command: sh -c "npm install && npm run serve"
