version: "3.8"

services:
  express:
    environment:
      MONGO_URL: "mongodb://mongo/todos"
      PORT: 5000
    build:
      context: ./backend
    ports:
      - 5000:5000
  vue:
    build:
      context: ./frontend
    ports:
      - 8080:8080
