version: "3.8"

services:
  mongo:
    image: mongo

  express:
    build:
      context: ./backend
    ports:
      - 5000:5000
    depends_on:
      - mongo

  vue:
    build:
      context: ./frontend
    ports:
      - 8080:8080
    depends_on:
      - express
